"""Add login, registration, roles, forms, and ensure Cylinder model is migrated.

Revision ID: 38d3629e8903
Revises: dddfd01d0285
Create Date: 2025-06-16 15:16:50.268960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38d3629e8903'
down_revision = 'dddfd01d0285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cylinder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cylinder_id_tag', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('reception_date', sa.DateTime(), nullable=True),
    sa.Column('delivery_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cylinder', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cylinder_creation_date'), ['creation_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_cylinder_cylinder_id_tag'), ['cylinder_id_tag'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cylinder', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cylinder_cylinder_id_tag'))
        batch_op.drop_index(batch_op.f('ix_cylinder_creation_date'))

    op.drop_table('cylinder')
    # ### end Alembic commands ###
