"""Crear tabla HistorialMovimiento para registro de entregas y recepciones

Revision ID: 6b0b6c130c54
Revises: 6f9cf9cdf3cc
Create Date: 2025-06-18 09:02:24.713847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b0b6c130c54'
down_revision = '6f9cf9cdf3cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historial_movimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cylinder_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tipo_movimiento', sa.String(length=20), nullable=False),
    sa.Column('fecha_movimiento', sa.DateTime(), nullable=False),
    sa.Column('nombre_contraparte', sa.String(length=150), nullable=True),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cylinder_id'], ['cylinder.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historial_movimiento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historial_movimiento_cylinder_id'), ['cylinder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_historial_movimiento_fecha_movimiento'), ['fecha_movimiento'], unique=False)
        batch_op.create_index(batch_op.f('ix_historial_movimiento_tipo_movimiento'), ['tipo_movimiento'], unique=False)
        batch_op.create_index(batch_op.f('ix_historial_movimiento_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historial_movimiento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historial_movimiento_user_id'))
        batch_op.drop_index(batch_op.f('ix_historial_movimiento_tipo_movimiento'))
        batch_op.drop_index(batch_op.f('ix_historial_movimiento_fecha_movimiento'))
        batch_op.drop_index(batch_op.f('ix_historial_movimiento_cylinder_id'))

    op.drop_table('historial_movimiento')
    # ### end Alembic commands ###
