"""Anadir nombre y apellidos a User

Revision ID: 6f9cf9cdf3cc
Revises: 38d3629e8903
Create Date: 2025-06-17 14:26:00.823519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f9cf9cdf3cc'
down_revision = '38d3629e8903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('apellidos', sa.String(length=128), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_user_apellidos'), ['apellidos'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_nombre'), ['nombre'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_nombre'))
        batch_op.drop_index(batch_op.f('ix_user_apellidos'))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.drop_column('apellidos')
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###
