"""Anadir marca color numero_serie a Cylinder

Revision ID: 909f4c6c354a
Revises: 6b0b6c130c54
Create Date: 2025-06-23 11:12:23.582616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '909f4c6c354a'
down_revision = '6b0b6c130c54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cylinder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marca', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('numero_serie', sa.String(length=80), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_cylinder_delivery_date'), ['delivery_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_cylinder_numero_serie'), ['numero_serie'], unique=False)
        batch_op.create_index(batch_op.f('ix_cylinder_reception_date'), ['reception_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cylinder', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cylinder_reception_date'))
        batch_op.drop_index(batch_op.f('ix_cylinder_numero_serie'))
        batch_op.drop_index(batch_op.f('ix_cylinder_delivery_date'))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.drop_column('numero_serie')
        batch_op.drop_column('color')
        batch_op.drop_column('marca')

    # ### end Alembic commands ###
