"""Anadir esta_activo a User

Revision ID: aab6c1f56d67
Revises: 
Create Date: 2025-06-26 11:50:22.567597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aab6c1f56d67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cylinder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cylinder_id_tag', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('reception_date', sa.DateTime(), nullable=True),
    sa.Column('delivery_date', sa.DateTime(), nullable=True),
    sa.Column('marca', sa.String(length=80), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('numero_serie', sa.String(length=80), nullable=True),
    sa.Column('esta_activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cylinder', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cylinder_creation_date'), ['creation_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_cylinder_cylinder_id_tag'), ['cylinder_id_tag'], unique=True)
        batch_op.create_index(batch_op.f('ix_cylinder_delivery_date'), ['delivery_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_cylinder_esta_activo'), ['esta_activo'], unique=False)
        batch_op.create_index(batch_op.f('ix_cylinder_numero_serie'), ['numero_serie'], unique=False)
        batch_op.create_index(batch_op.f('ix_cylinder_reception_date'), ['reception_date'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('nombre', sa.String(length=64), nullable=True),
    sa.Column('apellidos', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('esta_activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_apellidos'), ['apellidos'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_esta_activo'), ['esta_activo'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_nombre'), ['nombre'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('historial_movimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cylinder_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tipo_movimiento', sa.String(length=20), nullable=False),
    sa.Column('fecha_movimiento', sa.DateTime(), nullable=False),
    sa.Column('nombre_contraparte', sa.String(length=150), nullable=True),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cylinder_id'], ['cylinder.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historial_movimiento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historial_movimiento_cylinder_id'), ['cylinder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_historial_movimiento_fecha_movimiento'), ['fecha_movimiento'], unique=False)
        batch_op.create_index(batch_op.f('ix_historial_movimiento_tipo_movimiento'), ['tipo_movimiento'], unique=False)
        batch_op.create_index(batch_op.f('ix_historial_movimiento_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historial_movimiento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historial_movimiento_user_id'))
        batch_op.drop_index(batch_op.f('ix_historial_movimiento_tipo_movimiento'))
        batch_op.drop_index(batch_op.f('ix_historial_movimiento_fecha_movimiento'))
        batch_op.drop_index(batch_op.f('ix_historial_movimiento_cylinder_id'))

    op.drop_table('historial_movimiento')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_nombre'))
        batch_op.drop_index(batch_op.f('ix_user_esta_activo'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_apellidos'))

    op.drop_table('user')
    with op.batch_alter_table('cylinder', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cylinder_reception_date'))
        batch_op.drop_index(batch_op.f('ix_cylinder_numero_serie'))
        batch_op.drop_index(batch_op.f('ix_cylinder_esta_activo'))
        batch_op.drop_index(batch_op.f('ix_cylinder_delivery_date'))
        batch_op.drop_index(batch_op.f('ix_cylinder_cylinder_id_tag'))
        batch_op.drop_index(batch_op.f('ix_cylinder_creation_date'))

    op.drop_table('cylinder')
    # ### end Alembic commands ###
